# Apply to all files without commiting:
#   pre-commit run --all-files
# Update this file:
#   pre-commit autoupdate
default_language_version:
  python: python3.11
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        args:
          - '--markdown-linebreak-ext=md'
      - id: check-case-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-yaml
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-xml
      - id: check-json
        exclude: .vscode
      - id: debug-statements
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: pretty-format-json
        exclude: .vscode
        args:
          - '--autofix'
          - "--indent=4"
  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: 'v0.5.1'
    hooks:
    - id: remove-print-statements
  - repo: 'https://github.com/PyCQA/autoflake'
    rev: v2.1.1
    hooks:
      - id: autoflake
        files: \.(py)$
        args:
          - "--in-place"
          - "--remove-all-unused-imports"
          - "--remove-duplicate-keys"
          - "--remove-unused-variables"
          - "--ignore-pass-statements"
  - repo: 'https://github.com/pycqa/isort'
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.(py)$
        args:
          - '--line-length=100'
  - repo: 'https://github.com/psf/black'
    rev: 23.3.0
    hooks:
      - id: black
        args:
          - "--preview"
          - "-l"
          - "100"
  - repo: 'https://github.com/PyCQA/flake8'
    rev: 6.0.0
    hooks:
      - id: flake8
        files: \.(py)$
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args:
        - -s
        - B113,B608,B307,B112
        - -x
        - "tests"
